require('dotenv').config('/');

module.exports = {
  local: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    pool: {
      min: 0,
      max: 500,
      idle: 5000,
    },
    dialect: 'mysql',
    dialectOptions: {
      multipleStatements: true,
    },
    migrationStorage: 'sequelize',
    migrationStorageTableName: 'sequelize_meta',
    timezone: '+00:00',
    logging: false,
  },
  test: {
    username: process.env.TEST_DB_USER,
    password: process.env.TEST_DB_PASSWORD,
    database: process.env.TEST_DB_NAME,
    host: process.env.TEST_DB_HOST,
    port: process.env.TEST_DB_PORT,
    pool: {
      min: 2,
      max: 10,
    },
    dialect: 'mysql',
    migrationStorage: 'sequelize',
    migrationStorageTableName: 'sequelize_meta',
    timezone: '+00:00',
    logging: false,
  },
  develop: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    pool: {
      min: 2,
      max: 10,
    },
    dialect: 'mysql',
    migrationStorage: 'sequelize',
    migrationStorageTableName: 'sequelize_meta',
    timezone: '+00:00',
    logging: false,
  },
  staging: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    pool: {
      min: 2,
      max: 10,
    },
    dialect: 'mysql',
    migrationStorage: 'sequelize',
    migrationStorageTableName: 'sequelize_meta',
    timezone: '+00:00',
    logging: false,
  },
  production: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    pool: {
      min: 2,
      max: 10,
    },
    dialect: 'mysql',
    migrationStorage: 'sequelize',
    migrationStorageTableName: 'sequelize_meta',
    timezone: '+00:00',
    logging: false,
  },
};
